spring:
  application:
    name: MonAirline

  datasource:
    url: jdbc:mysql://localhost:3306/flightdb
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expiration: 2592000000 # 30 days in milliseconds
